### ISSUE TITLE
предложение:переписать на жава скрипт

### ISSUE THREAD

**Issue by VityaSchel** [fuad00/dodopizza-abuse#1]

**Comment by VityaSchel** [comment]
ну потому что питон это позерство

**Comment by fuad00** [comment]
> ну потому что питон это позерство

руки в ноги!

**Comment by hrrrrustic** [comment]
Я вообще без понятия как я сюда попал, но с ишуей соглы, на питоне писать - себя не уважать

**Comment by fuad00** [comment]
> на питоне писать - себя не уважать
жду пул реквеста)

**Comment by fuad00** [comment]
> на питоне писать - себя не уважать

жду пул реквеста)
